### ISSUE TITLE
Feat: seek part in song

### ISSUE THREAD

**Issue by jessej-samuel** [jessej-samuel/spotipy#2]
The user must be able to click on the play bar and go to a specific portion of a song

**Comment by VenomFate-619** [comment]
Can I do it?

**Comment by jessej-samuel** [comment]
@VenomFate-619  Yes sure! I'll assign you the issue.

**Comment by jessej-samuel** [comment]
@VenomFate-619 Have you started working on this issue?

**Comment by VenomFate-619** [comment]
Yes

**Comment by VenomFate-619** [comment]
Is there any state through which I can know that song is being played or not ?
I think maybe it is  related to the` PLAYER_STATE_SELECTED` reducer , what does this reducer returns ?

**Comment by jessej-samuel** [comment]
> Is there any state through which I can know that song is being played or not ? I think maybe it is related to the` PLAYER_STATE_SELECTED` reducer , what does this reducer returns ?

Yea, if it's 1 when the song is being played, and 0nif no song is played

**Comment by mantevian** [comment]
Hello! I found this repo from Hacktoberfest, and before I commented here I wanted to try if I could actually do this since I have almost no experience with React, but it seems like I have done this! If you'd like, I can make a PR already :D
But I have a question: since the song progress bar is so small in height, could it be increased a little bit so it's easier to click on it?

**Comment by jessej-samuel** [comment]
Hi @mantevian ! Yes, it can increase a little bit, but I would prefer it to stay as it is normally, and **increase in height on hover**

**Comment by mantevian** [comment]
Done!

**Comment by jessej-samuel** [comment]
#15 fixes this issue.
